/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOraclePoS, IOraclePoSInterface } from "../IOraclePoS";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_referenceDay",
        type: "uint256",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "uint256",
        name: "referenceDay",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "referenceBlock",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "supplyCap",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxStakingDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxConsumptionRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minConsumptionRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mintingPeriod",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "scale",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLastIndexedDay",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_referenceDay",
        type: "uint256",
      },
    ],
    name: "isDayIndexed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_referenceDay",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_referenceBlock",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_currentSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_supplyCap",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxStakingDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxConsumptionRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minConsumptionRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_mintingPeriod",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_scale",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "updateIndex",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOraclePoS__factory {
  static readonly abi = _abi;
  static createInterface(): IOraclePoSInterface {
    return new utils.Interface(_abi) as IOraclePoSInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOraclePoS {
    return new Contract(address, _abi, signerOrProvider) as IOraclePoS;
  }
}
