/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISilicaAccountFactory,
  ISilicaAccountFactoryInterface,
} from "../ISilicaAccountFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sellerAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "erc20TokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "oracleType",
        type: "uint16",
      },
    ],
    name: "NewSilicaAccount",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "erc20TokenAddress",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "oracleType",
        type: "uint16",
      },
    ],
    name: "createSilicaAccount",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sellerAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "erc20TokenAddress",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "oracleType",
        type: "uint16",
      },
    ],
    name: "getDeterministicAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISilicaAccountFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ISilicaAccountFactoryInterface {
    return new utils.Interface(_abi) as ISilicaAccountFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISilicaAccountFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISilicaAccountFactory;
  }
}
