/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISilicaFunctions,
  ISilicaFunctionsInterface,
} from "../ISilicaFunctions";

const _abi = [
  {
    inputs: [],
    name: "amountDueAtContractEnd",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "amountLocked",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "amountOwedNextUpdate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "day",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_networkHashrate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_networkReward",
        type: "uint256",
      },
    ],
    name: "defaultContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_networkHashrate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_networkReward",
        type: "uint256",
      },
    ],
    name: "fulfillUpdate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_paymentToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_hashrate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_contractPeriod",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_reservedPrice",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_costToCreateContract",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "day",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "remainingBalance",
        type: "uint256",
      },
    ],
    name: "tryToCompleteContract",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "day",
        type: "uint32",
      },
    ],
    name: "tryToExpireContract",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "day",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_networkHashrate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_networkReward",
        type: "uint256",
      },
    ],
    name: "tryToStartContract",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISilicaFunctions__factory {
  static readonly abi = _abi;
  static createInterface(): ISilicaFunctionsInterface {
    return new utils.Interface(_abi) as ISilicaFunctionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISilicaFunctions {
    return new Contract(address, _abi, signerOrProvider) as ISilicaFunctions;
  }
}
