/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISilicaAccountEvents,
  ISilicaAccountEventsInterface,
} from "../ISilicaAccountEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "silicaAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "paymentTokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "resourceAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "period",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "reservedPrice",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "oracleType",
        type: "uint16",
      },
    ],
    name: "NewSilicaContract",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "Received",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "day",
        type: "uint256",
      },
    ],
    name: "SilicaAccountUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawExcessReward",
    type: "event",
  },
];

export class ISilicaAccountEvents__factory {
  static readonly abi = _abi;
  static createInterface(): ISilicaAccountEventsInterface {
    return new utils.Interface(_abi) as ISilicaAccountEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISilicaAccountEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISilicaAccountEvents;
  }
}
