/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ISilicaAccountFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createSilicaAccount(address,uint16)": FunctionFragment;
    "getDeterministicAddress(address,address,uint16)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createSilicaAccount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeterministicAddress",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSilicaAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeterministicAddress",
    data: BytesLike
  ): Result;

  events: {
    "NewSilicaAccount(address,address,address,uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewSilicaAccount"): EventFragment;
}

export type NewSilicaAccountEvent = TypedEvent<
  [string, string, string, number] & {
    sellerAddress: string;
    contractAddress: string;
    erc20TokenAddress: string;
    oracleType: number;
  }
>;

export class ISilicaAccountFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISilicaAccountFactoryInterface;

  functions: {
    createSilicaAccount(
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getDeterministicAddress(
      sellerAddress: string,
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createSilicaAccount(
    erc20TokenAddress: string,
    oracleType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getDeterministicAddress(
    sellerAddress: string,
    erc20TokenAddress: string,
    oracleType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createSilicaAccount(
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getDeterministicAddress(
      sellerAddress: string,
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "NewSilicaAccount(address,address,address,uint16)"(
      sellerAddress?: string | null,
      contractAddress?: string | null,
      erc20TokenAddress?: null,
      oracleType?: null
    ): TypedEventFilter<
      [string, string, string, number],
      {
        sellerAddress: string;
        contractAddress: string;
        erc20TokenAddress: string;
        oracleType: number;
      }
    >;

    NewSilicaAccount(
      sellerAddress?: string | null,
      contractAddress?: string | null,
      erc20TokenAddress?: null,
      oracleType?: null
    ): TypedEventFilter<
      [string, string, string, number],
      {
        sellerAddress: string;
        contractAddress: string;
        erc20TokenAddress: string;
        oracleType: number;
      }
    >;
  };

  estimateGas: {
    createSilicaAccount(
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getDeterministicAddress(
      sellerAddress: string,
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createSilicaAccount(
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getDeterministicAddress(
      sellerAddress: string,
      erc20TokenAddress: string,
      oracleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
